### ISSUE TITLE
Assembly signing not supported on .NET Core

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/GeoAPI#27]
Remove assembly signing or we will never have crossplatform development support. We can always sign the published dll's in the CI-server for the windows-only targets.

Feedback requested, from others @DGuidi @FObermaier

**Comment by xivk** [comment]
Ignore previous comments, I can disable this per-platform.

**Comment by DGuidi** [comment]
I always considered assembly signing a [PITA](http://www.urbandictionary.com/define.php?term=P.I.T.A), maybe we can simply get rid of it also in windows targets?
Anyway, removing signing in windows targets should be considered a breaking change, because signed dll's than cannot use NTS dlls anymore.

**Comment by bastien-hofmann** [comment]
Hello,

Maybe I am missing something, but it seems that removing assembly signing from the .NET Standard version only is preventing to provide .NET Standard libraries referencing GeoAPI to .NET Framework projects referencing GeoAPI too.

I attached an example project to illustrate the issue:
[GeoApiSigningTest.zip](https://github.com/NetTopologySuite/GeoAPI/files/1397732/GeoApiSigningTest.zip)

I have a TestNetStandardNuGetLib project targeting .NET Standard 1.0, and referencing GeoAPI 1.7.5-pre006. Since I'm targeting .NET Standard 1.0, it references the  .NET Standard 1.0 unsigned version of GeoAPI.

I have another project, TestNetFrameworkApp, targeting .NET Framework 4.5.2, also referencing GeoAPI 1.7.5-pre006. However since I'm targeting the .NET Framework, it actually references the .NET 4.5 signed version of GeoAPI.

When I try to reference TestNetStandardNuGetLib in TestNetFrameworkApp and use some GeoAPI related code, I can't compile my project because these two projects are referencing what appears to the compiler to the be two different assemblies since they have a different signature.

A workaround for me is to do multi targeting in my TestNetStandardNuGetLib, so the .NET 45 version of my lib would reference the .NET 45 version of GeoAPI. But then, .NET Standard projects referencing my lib will have to do the same thing, etc.

I am curious, why are you saying that assembly signing is not supported in .NET Core? I have .NET Core projects referencing signed .NET Standard assemblies like Newtonsoft.Json apparently without issues.

Best regards.
