### ISSUE TITLE
Building against NetCore 2.0 (netcoreapp2.0) on Linux

### ISSUE THREAD

**Issue by jhidding** [NetTopologySuite/GeoAPI#38]
Hi,
I managed, with some effort, to build GeoAPI for the netcoreapp2.0 target. I had to disable SignAssembly and remove Consts.Product from the AssemblyInfo. Unit tests passed. If you like I can create a pull request.
Cheers!

**Comment by airbreather** [comment]
What advantages are there to adding a `netcoreapp2.0` target?  We already target `netstandard2.0`, which supports nearly everything we do except a couple of things that I [called out](https://github.com/NetTopologySuite/GeoAPI/blob/8635a94e7f795b1fa55021a379492b5778ae7f67/src/GeoAPI/GeoAPI.csproj#L92-L95) as not being actually all that desirable.

**Comment by jhidding** [comment]
I don't know, I'm new to building C# apps. Indeed using target netstandard2.0 also works! However to also build the unittests I need to add netstandard2.0 to the targets. There is also an issue with signing the assembly, which only works on windows.

**Comment by airbreather** [comment]
> However to also build the unittests I need to add netstandard2.0 to the targets.

Our travis configuration uses mono for this part, in lieu of either making multiple .csproj files, multi-targeting the test project (which is insufficient to test all the combinations... we'd need something more like Microsoft/vstest#1013), or something else I can't think of quite yet... it's not 100% ideal, but maybe we could consider using .NET Core instead of .NET 4.5.

> There is also an issue with signing the assembly, which only works on windows.

Are you using MSBuild or "`dotnet build`"?  You should be using MSBuild, which builds this just fine on Linux (I'm **pretty sure** it's signing the assemblies too, though I might be misremembering... it's been a while since I fired up WSL or a VM).

See our [.travis.yml](https://github.com/NetTopologySuite/GeoAPI/blob/8635a94e7f795b1fa55021a379492b5778ae7f67/.travis.yml) and [build.sh](https://github.com/NetTopologySuite/GeoAPI/blob/8635a94e7f795b1fa55021a379492b5778ae7f67/build.sh) -- we actually use Travis CI to build and test (though the NuGet packages are created through TeamCity), and that's running on Linux.

**Comment by jhidding** [comment]
I'm using `dotnet bulid`, I'll try `msbuild`. Thanks!

**Comment by airbreather** [comment]
@jhidding any remaining difficulties with this one?

**Comment by jhidding** [comment]
Sorry, had to work on some other things in the mean while. I'll try building MSbuild from source and go from there.

**Comment by FObermaier** [comment]
Any update or can this be closed?
