### ISSUE TITLE
Should ILineString include Count?

### ISSUE THREAD

**Issue by bricelam** [NetTopologySuite/GeoAPI#48]
It's [on LineString](https://github.com/NetTopologySuite/NetTopologySuite/blob/2022f0dbaa73269029622894982d95aad2e60bb5/NetTopologySuite/Geometries/LineString.cs#L473) (as an alias of `NumPoints`) but not the interface.

**Comment by airbreather** [comment]
IMO it doesn't make sense to have two properties on the interface that are defined to mean the exact same thing.  It's also not on JTS's `LineString`, nor does it appear to have ever been there (though it's been on NTS's `LineString` since [as far back as the Git history goes](https://github.com/NetTopologySuite/NetTopologySuite/blob/b6f273231aa4931af92ac12cec7232b6d8f42cfe/NetTopologySuite/Geometries/LineString.cs#L459-L469), so it beats me where this came from).

**Comment by bricelam** [comment]
Personally, I love having both. One to make it OGC-compliant (NumPoints) and one to make it .NET idiomatic (Count). It's a shame C# doesn't have extension properties yet...

``` C#
// I <3 OGC
for (var n = 0; n < lineString.NumPoints; n++)
{
    var coordinate = lineString.GetPointN(n).Coordinate;
}

// I <3 C#
for (var i = 0; i < lineString.Count; n++)
{
    var coordinate = lineString[i];
}
```

**Comment by bricelam** [comment]
Note, `IGeometryCollection` also has both `NumGeometries` and `Count`.

**Comment by FObermaier** [comment]
> It's also not on JTS's LineString, nor does it appear to have ever been there (though it's been on NTS's LineString since as far back as the Git history goes, so it beats me where this came from)

It is in the block 
```C#
/* BEGIN ADDED BY MPAUL42: monoGIS team */

...

/* END ADDED BY MPAUL42: monoGIS team */
```
which explains where it came from. It has been there ever since I worked with NTS, perhaps an attempt to .Net-ify the solution. I don't even know if GeoAPI has factored out of the project at that point in time.
@DGuidi?

In my opinion the comparison with `IGeometryCollection.Count` is not valid since `ILineString.NumPoints` returns the number of coordinates that make up the `ILineString` and not a number of geometries.

**Comment by bricelam** [comment]
I'm fine closing this. I just noticed it and wanted to make sure it was by design.
